### ISSUE TITLE
Post-list layout and behaviour

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#37]
- [x] ~~There will be a "leer mas" button at the end of the list. (Prefetching? https://github.com/worona/saturn-app-theme-worona/issues/36)~~
- [ ] ~~https://github.com/worona/saturn-app-theme-worona/issues/39 Study if we can change the URL as the user goes to the next pages in that list.~~
- [x] Number of posts in the post-lists will be limited to 10. (Configurable from the dashboard? https://github.com/worona/saturn-app-theme-worona/issues/38)
- [x] https://github.com/worona/saturn-app-theme-worona/issues/7 We maintain the current layout of cards
